# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPathOrchestratorConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

# Download secure file v1
# Download a secure file to the agent machine.
- task: DownloadSecureFile@1
  inputs:
    secureFile: "NuGet Test Developer.cer" # string. Required. Secure File"". 
    #retryCount: '8' # string. Retry Count. Default: 8.
    #socketTimeout: # string. Socket Timeout.

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'nuget sign $(Build.ArtifactStagingDirectory)/**/*.nupkg -CertificatePath $(mySecureFile.secureFilePath)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'dd4a15f0-4dce-4f4a-beeb-5e8bfdb0d35e/dc984a49-3241-496c-b80e-17f8d1e7a1eb'